#!/bin/sh
mvn clean package && docker build -t shubhamdockerhub/SimpleMicroProfileApp .
docker rm -f SimpleMicroProfileApp 2>/dev/null || true && docker run -it --name SimpleMicroProfileApp -p 8080:8080 -p 4848:4848 -p 8181:8181 --name SimpleMicroProfileApp shubhamdockerhub/SimpleMicroProfileApp
